SumoLogic/sumologic-terraform-provider

- sumologic/sumologic_client.go
Adds a very simplistic rate limiter based on Sumo's published 240 requests/minute limit.
The ticker is global to allow for concurrent operations within Terraform.
I originally considered using a moving bucket, but then realised that I quite often ran `terraform plan` multiple times per minute, so it'd be easy to go over the limits with multiple runs without using a slow tick.
In my work trialling SumoLogic for my work I've frequently hit the rate limit without this.
> Add simple rate limit to API methods

- sumologic/resource_sumologic_polling_source.go
- sumologic/sumologic_polling_source.go
Adding this schema allows for the computed URL of the polling_source resource to be used as a SNS topic subscription https endpoint.
> Add 'url' schema to polling_source resource for SNS notifications

- docs/d/sumologic_collector.md
- sumologic/data_source_sumologic_collector.go
- sumologic/data_source_sumologic_collector_test.go
- sumologic/provider.go
new terraform data source for SumoLogic collectors.
the acceptance test for the new data source currently fails on the test tear-down because of an issue in the collector resource; the test will fix itself once that issue with the collector resource is fixed
> issue-11 terraform data source for sumo collector

- sumologic/resource_sumologic_collector.go
- sumologic/resource_sumologic_collector_test.go
Fix for [issue 19](https://github.com/SumoLogic/sumologic-terraform-provider/issues/19): terraform apply doesn't re-create a collector after it has been deleted manually
> issue-19 re-create collector if manually deleted

- sumologic/resource_sumologic_role.go
When `users` or `capabilities` has multiple value, it cause diff always...
@frankreno Sorry, I didn't notice this issue when I test.
> fix random order issue of string list

- docs/r/sumologic_http_source.md
- sumologic/resource_sumologic_http_source.go
- sumologic/resource_sumologic_http_source_test.go
- sumologic/sumologic_sources.go
This provides the initial work for supporting import of HTTP source. Unlikely collectors, an ID-only passthrough import is not possible. Instead I elected to do `terraform import sumologic_http_source.<name> <collector_id>/<source_id>` and split on the `/` in order to populate the 2 required IDs. 
Still todo:
* Add some extra validation, e.g. ensuring 2 IDs are passed
* Add tests against that
* Add importers to other comparable resources
I was able to build this and use it to quickly import something so I figured I'd open the PR until I have a chance to finish it up
> Add import support for http sources

- docs/r/sumologic_http_source.md
> docs: fix typo in http_source import example

- docs/r/sumologic_http_source.md
Doesn't seem like a good default to be suggesting by example
Closes #35
> docs: remove message_per_request from http_source example

- sumologic/sumologic_cloudsyslog_source.go
The cloud syslog token was perviously always empty because the token is returned from the API on the `token` key.
> Corrects the JSON tag for cloud syslog token

- sumologic/sumologic_client.go
Fixes issue #58 
The `ErrorResponse` no longer matches the API, I noticed that delete was already doing it this way:
https://github.com/SumoLogic/sumologic-terraform-provider/blob/master/sumologic/sumologic_client.go#L264-L266
With this simpler approach, the API developers can change the error response schema and we would not have to do anything.
> Simplify error handling

- main.go
Getting rid of the following warning on `make install`:
```
can't load package: package github.com/SumoLogic/sumologic-terraform-provider/sumologic: case-insensitive import collision: "github.com/SumoLogic/sumologic-terraform-provider/sumologic" and "github.com/sumologic/sumologic-terraform-provider/sumologic"
mkdir -p dist/darwin_amd64; \
go build -o dist/darwin_amd64/terraform-provider-sumologic
[...]
```
Not sure if anyone else sees it (could it be Mac-specific as Mac handles some things case insensitive?)
> Fixing the import warning

- README.md
- docs/r/sumologic_folder.md
- go.mod
- sumologic/provider.go
- sumologic/resource_sumologic_folder.go
- sumologic/resource_sumologic_folder_test.go
- sumologic/sumologic_client.go
- sumologic/sumologic_cloudsyslog_source.go
- sumologic/sumologic_collectors.go
- sumologic/sumologic_folder.go
- sumologic/sumologic_http_source.go
- sumologic/sumologic_ingest_budget.go
- sumologic/sumologic_polling_source.go
- sumologic/sumologic_roles.go
- sumologic/sumologic_sources.go
- sumologic/sumologic_users.go
Adding folder management plugin for terraform provider. Tested using acceptance tests and folder CRUD on production deployment.
Used these references for CRUD operations:
Create: https://nite-api.sumologic.net/docs/#operation/createFolder
Read: https://nite-api.sumologic.net/docs/#operation/getFolder
Update: https://nite-api.sumologic.net/docs/#operation/updateFolder
Delete: https://nite-api.sumologic.net/docs/#operation/beginAsyncDelete, https://nite-api.sumologic.net/docs/#operation/getAsyncDeleteStatus
As folder management is V2 (not V1), I updated the URLs in sumologic_client.go and request paths extensions in the respective files.
@frankreno
> Adding folder management plugin for terraform provider

- README.md
- docs/sumologic-provider.md
- go.mod
- go.sum
- sumologic/provider.go
- sumologic/sumologic_client.go
Adding the ability to provide explicitly the baseURL (the API URL) if none of the built-in ones provided by Sumo Logic is what we what to interface against.
> BaseURL support

- docs/r/sumologic_collector.md
- docs/r/sumologic_http_source.md
- sumologic/resource_sumologic_collector.go
- sumologic/sumologic_collectors.go
- sumologic/sumologic_sources.go
This PR adds the ability to `terraform import` collectors by `name` and sources by `collectorName/sourceName`.  We will use this in the future for our Kubernetes offering in https://github.com/SumoLogic/sumologic-kubernetes-collection
It also switches to the new API to get a collector by name, rather than iterating through all collectors.
Test plan:
1. Create collector with http source using `terraform apply`:
```
provider "sumologic" { }
resource "sumologic_collector" "c1" {
name = "rmiller-test-hosted"
}
resource "sumologic_http_source" "h1" {
name = "rmiller-test-http_rename"
category = "test_cat"
collector_id = "${sumologic_collector.c1.id}"
}
```
2. Delete `terraform.tfstate*` files
3. `terraform import sumologic_collector.c1 rmiller-test-hosted`
4. `import sumologic_http_source.h1 …
> Add collector import by name functionality

- sumologic/sumologic_sources.go
Noticed a bug while working on https://github.com/SumoLogic/sumologic-terraform-provider/pull/76 where importing a source and then changing its name causes a 2nd source to be created in Sumo. Frank realized it was due to this `ForceNew` logic which re-creates the resource (delete + create) but we simply want to update the source, not recreate it for modifiable fields like `name` and `fields`. I have left it recreating the source for "non-modifiable" fields like `cutoff_relative_time` and `collector_id`.
Test plan:
1. Create collector with http source using `terraform apply`:
```
provider "sumologic" { }
resource "sumologic_collector" "c1" {
name = "rmiller-test-hosted"
}
resource "sumologic_http_source" "h1" {
name = "rmiller-test-http_rename"
category = "test_cat"
collector_id = …
```
> Don't recreate source on name/fields change

- go.mod
- go.sum
- main.go
For terraform 12 go.mod was introduced, strangely requiring this module
at an older version and a different path. I think this caused older code to build,
which caused the `token` output to be blank on a sumologic_cloudsyslog_source
resource.
By removing the odd go.mod require line, and making the import in main match the
module name in go.mod (case sensitive), everything seems to build and work as expected.
Also commits go.sum as good practice.
> Fixes token bug in cloudsyslog_source resource

- sumologic/sumologic_sources.go
This fixes a bug that caused TF to crash if you try to import a source with an invalid collector name, or a valid collector name and invalid source name.  Now it will error gracefully with an error message:
```
terraform $ tf import sumologic_http_source.h1 "not-a-real-collector/not-a-real-source"
sumologic_http_source.h1: Importing from ID "not-a-real-collector/not-a-real-source"...
Error: collector with name 'not-a-real-collector' does not exist
```
```
terraform $ tf import sumologic_http_source.h1 "rmiller-test-hosted/not-a-real-source"
sumologic_http_source.h1: Importing from ID "rmiller-test-hosted/not-a-real-source"...
Error: source with name 'not-a-real-source' does not exist
```
> Fix source import for missing collector/source

- .gitignore
- go.sum
- sumologic/provider.go
This PR updates the TF `provider` to attempt endpoint redirection if neither `endpoint` nor `base_url` are specified.  This allows a customer to only specify `access_id` and `access_key` and it will resolve their correct endpoint `base_url` by checking the 301 redirection response from prod.
Tested with configuration from US2 access key/id (and no `base_url` or `endpoint` specified).
> Support endpoint redirection to make base_url optional

- docs/r/sumologic_polling_source.md
`url` is supported by the schema of `polling_source`:
https://github.com/SumoLogic/sumologic-terraform-provider/blob/master/sumologic/resource_sumologic_polling_source.go#L33-L38
This URL is needed to if you want to configure S3 to notify SNS of new objects and then SNS to notify Sumo Logic via HTTP.
The `url` attribute for a polling source would be passed to a `aws_sns_topic_subscription` resource.
> polling: document "url" attribute (for SNS)

- LICENSE
We are switching from the Apache license to the mozilla license to comply with hashicorp's rules regarding terraform providers.
> change license from apache to mozilla

- sumologic/resource_sumologic_content_test.go
- sumologic/resource_sumologic_extraction_rule.go
- sumologic/resource_sumologic_role.go
- sumologic/resource_sumologic_user.go
- sumologic/sumologic_client.go
The makefile has the command `make lint`
Fixed the non collector errors from this. 
- Mainly removing unused functions
- not using wrapper function for time `tick` as it leaks and is not cleaned up by garbage collector
Plan is to add this linter as one of the tasks on our travis build so that we do not add bad code moving forward. 
The terraform linter will be added as a github action unless we can also add that to the travis build.
> fix errors from the golangcli-lint

- README.md
Was getting 
```
../../go/pkg/mod/github.com/hashicorp/go-getter@v1.4.1/get_http.go:91:24: g.Header.Clone undefined (type http.Header has no field or method Clone)
../../go/pkg/mod/github.com/hashicorp/go-getter@v1.4.1/get_http.go:172:24: g.Header.Clone undefined (type http.Header has no field or method Clone)
make: *** [install] Error 2
```
with go 1.11
this function is added in go 1.13
https://golang.org/pkg/net/http/#Header.Clone
> update README.md with new golang version requirements
