sumologic/sumologic_polling_source.go

Previous PR incorrectly set URL to type bool.

Set URL to type string (not bool)

---

README.md
sumologic/provider.go

Support for SUMOLOGIC_ENVIRONMENT environment variable
[Issue 12](https://github.com/SumoLogic/sumologic-terraform-provider/issues/12)

ISSUE-12 environment variable to specify sumologic environment

---

sumologic/sumologic_client.go

[issue 14 blank error message with incorrect sumo environment](https://github.com/SumoLogic/sumologic-terraform-provider/issues/14)

issue-14 blank error message when incorrect sumo environment is specified

---

sumologic/resource_sumologic_collector.go
sumologic/resource_sumologic_collector_test.go

fix for [issue 17](https://github.com/SumoLogic/sumologic-terraform-provider/issues/17)

issue-17 collector name change should not force creation of new resource

---

docs/README.md

update docs' readme to point at the documentation for the sumologic_collector data source

update docs readme with sumologic_collector data source

---

docs/r/sumologic_collector.md
sumologic/resource_sumologic_collector.go
sumologic/resource_sumologic_collector_test.go

fix for [issue 25](https://github.com/SumoLogic/sumologic-terraform-provider/issues/25)

terraform import for sumologic_collector

---

sumologic/provider.go

check access_id and access_key are set and error if not
fix for [issue-27](https://github.com/SumoLogic/sumologic-terraform-provider/issues/27)

issue-27 provider attributes check

---

docs/sumologic-provider.md

Match reality
https://github.com/SumoLogic/sumologic-terraform-provider/blob/c6e365ae832848d8f5416fa4dfb9ae944f0719e5/sumologic/provider.go#L14
https://github.com/SumoLogic/sumologic-terraform-provider/blob/c6e365ae832848d8f5416fa4dfb9ae944f0719e5/sumologic/provider.go#L17

Update default environment docs

---

sumologic/provider.go
sumologic/resource_sumologic_role.go
sumologic/resource_sumologic_role_test.go
sumologic/sumologic_roles.go
sumologic/sumologic_roles_test.go

Fix part of https://github.com/SumoLogic/sumologic-terraform-provider/issues/41 .
Our org use SAML, so I don't need User API support. So, just adding Role API support.

Role API support

---

docs/r/sumologic_role.md

As I promised at https://github.com/SumoLogic/sumologic-terraform-provider/pull/51#issuecomment-506802335, I send doc PR. @frankreno

add doc for role resource

---

sumologic/provider.go
sumologic/resource_sumologic_scheduled_view.go
sumologic/sumologic_scheduled_views.go

Adding support for [Scheduled Views](https://api.sumologic.com/docs/#tag/scheduledViewManagement).
- Done by inspiration from User management
- Tested in practice with `apply`, `destroy`.

Scheduled Views

---

docs/README.md
docs/r/sumologic_scheduled_view.md

Adding docs for `scheduled_view` support added in #67.

Adding docs for scheduled_view

---

docs/README.md
docs/r/sumologic_collector.md
sumologic/data_source_sumologic_collector.go
sumologic/resource_sumologic_collector.go
sumologic/sumologic_collectors.go
sumologic/sumologic_sources.go

This PR adds the new fields support to collectors and sources.

Add fields

---

sumologic/sumologic_scheduled_views.go

Fixes #80. Adding missing `/v1` in the URL

---

sumologic/provider.go
sumologic/resource_partition.go
sumologic/resource_sumologic_partition.go
sumologic/sumologic_partition.go

Adding support for partition
inspired from @mccartney

Partition Support

---

sumologic/resource_sumologic_partition.go
sumologic/resource_sumologic_partition_test.go
sumologic/sumologic_partition.go

There were some errors I found the with partitions provider
- Decommission was originally done as delete, but this actually a post so `terraform destroy` would not work
- `DiffSuppressFunc` was not being used properly and was still requiring update on apply
Fixed these bugs and wrote acceptance tests
Note: `retention_period` can only be increased through terraform once created as the API call requires `reduceRetentionPeriodImmediately` if `retention_period` is lowered

fix errors in the partitions provider and write acceptance test

---

sumologic/provider.go
sumologic/sumologic_client.go

Fix crash and invalid init

---

.travis.yml
sumologic/provider_test.go
sumologic/resource_sumologic_content_test.go
sumologic/resource_sumologic_extraction_rule_import_test.go
sumologic/resource_sumologic_extraction_rule_test.go
sumologic/resource_sumologic_folder_test.go
sumologic/resource_sumologic_partition_test.go
sumologic/resource_sumologic_role_import_test.go
sumologic/resource_sumologic_role_test.go
sumologic/resource_sumologic_user_import_test.go
sumologic/resource_sumologic_user_test.go
travis/run_on_non_pull_requests

- `make test` for latest commit in PRs
- `make testacc` for latest commit in master or branches within repo
- turn on travis for all branches

Ssain update travis pr builder

---

sumologic/resource_sumologic_content.go
sumologic/resource_sumologic_content_test.go
sumologic/sumologic_content.go

- Checking if the content exists after the test was broken
- Terraform stopped liking \n in our JSON so removed that

Fix Content create and update test failures

---

sumologic/sumologic_partition.go

Partition api started giving 404 so changing test

partition api status code change fix failing test

---

sumologic/sumologic_client.go

Adding a user-agent header for analytics purposes

add user-agent to request for tracking terraform usage

---

scripts/changelog-links.sh

adding the last script from the other terraform repos

add change log script

---

sumologic/fields_map.go
sumologic/resource_sumologic_user_test.go

Remove the dependency on `fields_map.go` for role ID. Create the role and then the user and use the given role id.

create user with role with dynamic role ID

---

website/docs/README.md
website/docs/d/caller_identity.html.markdown
website/docs/d/collector.html.markdown
website/docs/d/personal_folder.html.markdown
website/docs/r/cloudsyslog_source.html.markdown
website/docs/r/collector.html.markdown
website/docs/r/collector_ingest_budget_assignment.html.markdown
website/docs/r/content.html.markdown
website/docs/r/extraction_rule.html.markdown
website/docs/r/folder.html.markdown
website/docs/r/http_source.html.markdown
website/docs/r/ingest_budget.html.markdown
website/docs/r/partition.html.markdown
website/docs/r/polling_source.html.markdown
website/docs/r/role.html.markdown
website/docs/r/scheduled_view.html.markdown
website/docs/r/user.html.markdown
website/sumologic.erb

- fixing some formatting issues
- adding partitions, content, extraction_rule

add new docs and fix some formatting on the old ones

---

sumologic/resource_sumologic_partition_test.go

Analytics tiers for partitions changed

fix partition analytics tiers

---

sumologic/data_source_sumologic_collector.go
sumologic/resource_sumologic_collector.go
sumologic/resource_sumologic_polling_source.go
sumologic/sumologic_sources.go

Recently came across [tfproviderlint](https://github.com/bflad/tfproviderlint) and tried it on this provider. The output is:
```
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_cloudsyslog_source_test.go:11:28: AT001: missing CheckDestroy
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_collector_test.go:183:28: AT001: missing CheckDestroy
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_http_source_test.go:11:28: AT001: missing CheckDestroy
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_http_source_test.go:27:28: AT001: missing CheckDestroy
/Users/ben/src/sumologic/sumologic-terraform-provider/sumologic/resource_sumologic_ingest_budget_test.go:10:28: …
```

fix schema issues raised by tfproviderlint

---

sumologic/resource_sumologic_partition_test.go

Reverts SumoLogic/sumologic-terraform-provider#131

Revert "fix partition analytics tiers"

---

sumologic/data_source_sumologic_collector_test.go
sumologic/resource_sumologic_cloudsyslog_source_test.go
sumologic/resource_sumologic_collector.go
sumologic/resource_sumologic_collector_test.go
sumologic/resource_sumologic_http_source_test.go
sumologic/resource_sumologic_ingest_budget_test.go
sumologic/sumologic_sources.go

first round of collector linter changes

linter change code cleanup, name changes, resourceData.Set()

---

sumologic/resource_sumologic_cloudsyslog_source_test.go

starting with the remaining linter recommended changes
* removing check destroy from cloudsyslog_source test 
* fixing up the code so the test actually tests stuff

add check destroy and clean up cloudsyslog_source test

---

sumologic/resource_sumologic_partition.go
sumologic/resource_sumologic_partition_test.go

* fix bug where isCompliant set to retention period
* make analytics tier optional like the API
* this will need to be updated when the new analytics tier are released

fix bug in partitions where isCompliant not set

---

README.md

- some updates to readme regarding using, developing, and testing of the provider

update readme with testing and dev info
